### ISSUE TITLE
Incorrect svg name

### ISSUE THREAD

**Issue by wave103x** [visualcrossing/WeatherIcons#1]
In **1st Set - Monochrome** icon's name with **space** instead of minus. 
 [clear day.svg](https://github.com/visualcrossing/WeatherIcons/blob/main/SVG/1st%20Set%20-%20Monochrome/clear%20day.svg)

**Comment by visualcrossing** [comment]
Thank you for reporting the issue! We have fixed the file name,

Regards
Visual Crossing Support
