### ISSUE TITLE
Incorrect icon file name snowd.svg

### ISSUE THREAD

**Issue by de-cocco** [visualcrossing/WeatherIcons#3]
Hi,

The name for an icon is incorrect: WeatherIcons/SVG/3rd  Set - Color/snowd.svg -> should be snow.svg as that would match the output of the weather API. 
Great project by the way, easy to use API and good selection of icons :)

Regards,

Dominic

**Comment by visualcrossing** [comment]
Thank you for your bug report! We have corrected the file name in the repository.

Regards
Visual Crossing Support

**Comment by de-cocco** [comment]
Thank you!
